config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  mount ActionCable.server => '/cable'

  get :dashboard, controller: :dashboard, action: :index

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'user/confirmations'
  }

  namespace :admin do
    resources :users, only: [:index]
    resources :teachers, only: :none do
      collection do
        get  'dashboard', action: :index
        get  'profile',   action: :show
        post 'profile',   action: :update
      end
    end
  end

  scope '/admin' do
    devise_for :teachers, controllers: {
      sessions: 'teachers/sessions',
      registrations: 'teachers/registrations',
      passwords: 'teachers/passwords',
      confirmations: 'teacher/confirmations'
    }
  end

  resources :subscriptions, only: [:new, :create] do
    collection do
      post :unsubscribe
      post :webhook
    end
  end

  resource :users, only: :none do
    collection do
      get  'dashboard', action: :index
      get  'profile',   action: :show
      post 'profile',   action: :update
    end
  end

  namespace 'users' do
    resources :notes, only: [:show]
  end

  resources :teachers, only: [:index, :show]
  resources :lessons, only: [:index, :create] do
    collection do
      get 'today', action: :today
    end
  end
  resources :books, except: [:edit]
  resources :notes, only: [:show, :update, :destroy]
  resources :account_settings, only: [:update]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  include AASM

  belongs_to :user

  aasm do
    state :unsubscribed, initial: true
    state :subscribed, :canceled

    event :unsubscribe do
      transitions from: :canceled, to: :unsubscribed
    end

    event :subscribe do
      transitions from: :unsubscribed, to: :subscribed
    end

    event :cancel do
      transitions from: :subscribed, to: :canceled
    end
  end

  def renew(subscription)
    update(end_date: Time.zone.now + 1.month, subscription: subscription)
  end

  def delete
    # update aasm_state
    update({})
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, except: :webhook
  protect_from_forgery except: :webhook

  def new
  end

  def create
    subscription = current_user.subscription
    subscription.subscribe do
      payment = CreditCardService.new(stripe_params)
      customer = payment.create_customer
      payment.charge
      subscription.update!(email: params[:stripeEmail], stripe_token: params[:stripeToken], user_id: current_user.id, customer_id: customer.id)
    end
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def unsubscribe
    Stripe.api_key = Rails.configuration.stripe[:secret_key]
    subscription = Stripe::Subscription.retrieve(current_user.subscription.subscription)
    subscription.delete()
    # subscription.delete(at_period_end: true)
  end

  def webhook
    event = Stripe::Event.retrieve(params[:id])
    case event.type
    when 'invoice.payment_succeeded'
      Subscription.find_by_customer_id(event.data.object.customer).renew(event.data.object.subscription)
    when 'customer.subscription.deleted'
      subscription = Subscription.find_by_customer_id(event.data.object.customer)
      subscription.cancel do
        subscription.delete
      end
    end
    render status: :ok, json: 'success'
  end

  private

  def stripe_params
    {
      email:       params[:stripeEmail],
      source:      params[:stripeToken],
      plan:        Plan.first.title
    }
  end
end

app/views/subscriptions/create.html.haml
%p
  お申し込みありがとうございました。
%div
  = link_to 'ダッシュボード', dashboard_users_path
  へ移動

app/views/subscriptions/new.html.erb
<div class="panel space-4">
  <div class="panel-header">
    お申し込み <span>5,000円（1ヶ月/週5回）</span>
  </div>

  <div class="panel-body">
    <% if current_user.subscription.subscribed? %>
    お申し込み済みです。次の引き落とし日は<%= current_user.subscription.end_date %>日の予定です。
    <% elsif current_user.subscription.canceled? %>
    解約手続き中です。
    <% elsif current_user.subscription.unsubscribed? %>

    <ul>
      <li>申し込むと、毎月1回引き落としがあります。（例：2日に申し込みした場合は翌月2日）</li>
      <li>解約は任意のタイミングで可能です。</li>
      <li>決済システムに<a href="https://stripe.com/jp/privacy">Stripe</a>を利用しています。</li>
      <li>ご不明な点はお問い合わせください。</li>
    </ul>
    <form action="/subscriptions" method="post" id="payment-form">
      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
      <div class="form-row">
        <div id="card-element">
        </div>
        <div id="card-errors" role="alert"></div>
      </div>
      <button class="order-button order-submit">お支払いを確定する</button>
    </form>

    <%= javascript_include_tag "https://js.stripe.com/v3/" %>
    <%= javascript_tag do %>
      window.publishableKey = '<%= Rails.configuration.stripe[:publishable_key] %>'
    <% end %>
    <%= javascript_include_tag "subscriptions" %>

    <% end %>

  </div>
</div>


<% if current_user.subscription.subscribed? %>
<div class="panel space-4">
  <div class="panel-header">
    解約
  </div>

  <div class="panel-body">
    <%= current_user.subscription.end_date %>日をもって解約します。
  </div>

  <div class="panel-footer">
    <form action="/subscriptions/unsubscribe" method="post" id="payment-form">
      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
      <button class="order-button order-submit">解約する</button>
    </form>
  </div>
</div>
<% end %>

<form action="/users/profile">
  <button class="order-button go-back">戻る</button>
</form>

app/views/subscriptions/unsubscribe.html.haml
%p
  ご利用ありがとうございました。
%div
  = link_to 'ダッシュボード', dashboard_users_path
  へ移動