config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  mount ActionCable.server => '/cable'

  get :dashboard, controller: :dashboard, action: :index

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'user/confirmations'
  }

  namespace :admin do
    resources :users, only: [:index]
    resources :teachers, only: :none do
      collection do
        get  'dashboard', action: :index
        get  'profile',   action: :show
        post 'profile',   action: :update
      end
    end
  end

  scope '/admin' do
    devise_for :teachers, controllers: {
      sessions: 'teachers/sessions',
      registrations: 'teachers/registrations',
      passwords: 'teachers/passwords',
      confirmations: 'teacher/confirmations'
    }
  end

  resources :subscriptions, only: [:new, :create] do
    collection do
      post :unsubscribe
      post :webhook
    end
  end

  resource :users, only: :none do
    collection do
      get  'dashboard', action: :index
      get  'profile',   action: :show
      post 'profile',   action: :update
    end
  end

  namespace 'users' do
    resources :notes, only: [:show]
  end

  resources :teachers, only: [:index, :show]
  resources :lessons, only: [:index, :create] do
    collection do
      get 'today', action: :today
    end
  end
  resources :books, except: [:edit]
  resources :notes, only: [:show, :update, :destroy]
  resources :account_settings, only: [:update]
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %base{ href: "/" }
    %title Mugsy's English
    = csrf_meta_tags
    = action_cable_meta_tag
    %link{ href: "https://s3-ap-northeast-1.amazonaws.com/rangoon/indigo-pink.css", rel: "stylesheet" }
    %link{ href: "https://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet" }
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Kanit'
    = stylesheet_link_tag "styles"
    = javascript_include_tag "application"

  %body
    = yield
    %angular
      = javascript_pack_tag "angular"
      - if teacher_signed_in?
        %script{ type: "text/javascript", src: "https://s3-ap-northeast-1.amazonaws.com/rangoon/skype-uri.js" }

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }/
    %title Mugsy's English
    = csrf_meta_tags
    = stylesheet_link_tag 'dashboard', media: 'all'
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Kanit'

  %body
    = yield